version: '2.0'
services:
  db:
    image: "${PGIMAGE}"   
    container_name: mobile-app-db 
    ports:
      - "${PGPORT}:5432"
    volumes:
      - "./init:/docker-entrypoint-initdb.d"
      - "./pgdata:/var/lib/postgresql/data"
    environment:
     POSTGRES_USER:     "${PGUSER}"
     POSTGRES_PASSWORD: "${PGPASSWORD}"
     POSTGRES_DB:       "${PGDATABASE}"

  mobile-app:
    image: "${APP_IMAGE}"
    depends_on:
      - db
    links:
      - "db:database"
    ports:
      - "9090:${APP_PORT}"
    environment:
     PGHOST: database 
     PGPORT: 5432 
